INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (21,'Antwerpen','Antwerpen');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (21,'Bruxelles','Bruxelles');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (21,'Hainaut','Hainaut');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (21,'Limburg','Limburg');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (21,'Li&eacute;ge','Li&eacute;ge');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (21,'Luxembourg','Luxembourg');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (21,'Namur','Namur');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (21,'Oost-Vlaanderen','Oost-Vlaanderen');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (21,'Vlaams-Brabant','Vlaams-Brabant');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (21,'Brabant wallon','Brabant wallon');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (21,'West-Vlaanderen','West-Vlaanderen');